POST http://localhost:8084/api/product
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{   "name":"product-name",   "code":"product-code",   "description":"product-description", "quantity":10 }

###
