POST http://localhost:8084/api/product
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{   "name":"product-name-2",   "code":"product-code-4",   "description":"product-description", "quantity":1200 }

###
